### ISSUE TITLE
麻烦继续更新 或者将一下怎么patch汉化

### ISSUE THREAD

**Issue by zimengle** [yeleo/Turtle-HD-Project-CN#1]
原版现在已经1.17.1了。。。

**Comment by yeleo** [comment]
已更新1.17.1版本

目前原版补丁导致法术书空白根本原因在patch-A.mpq文件解包后的DBFilesClient文件夹下的Spell.dbc数据库文件中没有汉化信息。只要将亚服客户端中的汉化信息(这个版本是patch-7.mpq)的数据更新上去就行。建议使用MPQEditor、DBCUtil工具进行解包。

**Comment by zimengle** [comment]
牛逼啊 我悟道了 按照你的方法 自己尝试了一下 可以了
